import json
import os
import sys

# English Restorations for all Japanese entries
EN_RESTORATIONS = {
    # Original Top 57
    "HND": {"city": "Tokyo", "name": "Haneda Airport"},
    "NRT": {"city": "Tokyo", "name": "Narita International Airport"},
    "KIX": {"city": "Osaka", "name": "Kansai International Airport"},
    "ITM": {"city": "Osaka", "name": "Itami Airport"},
    "NGO": {"city": "Nagoya", "name": "Chubu Centrair International Airport"},
    "FUK": {"city": "Fukuoka", "name": "Fukuoka Airport"},
    "CTS": {"city": "Sapporo", "name": "New Chitose Airport"},
    "OKA": {"city": "Okinawa", "name": "Naha Airport"},
    "AOJ": {"city": "Aomori", "name": "Aomori Airport"},
    "MSJ": {"city": "Misawa", "name": "Misawa Airport"},
    "HAK": {"city": "Hakodate", "name": "Hakodate Airport"},
    "AKJ": {"city": "Asahikawa", "name": "Asahikawa Airport"},
    "MMB": {"city": "Memanbetsu", "name": "Memanbetsu Airport"},
    "OBO": {"city": "Obihiro", "name": "Tokachi-Obihiro Airport"},
    "KUH": {"city": "Kushiro", "name": "Tancho Kushiro Airport"},
    "SDJ": {"city": "Sendai", "name": "Sendai Airport"},
    "KMQ": {"city": "Komatsu", "name": "Komatsu Airport"},
    "MYJ": {"city": "Matsuyama", "name": "Matsuyama Airport"},
    "HIJ": {"city": "Hiroshima", "name": "Hiroshima Airport"},
    "TAK": {"city": "Takamatsu", "name": "Takamatsu Airport"},
    "UKB": {"city": "Kobe", "name": "Kobe Airport"},
    "KOJ": {"city": "Kagoshima", "name": "Kagoshima Airport"},
    "KMI": {"city": "Miyazaki", "name": "Miyazaki Airport"},
    "NGS": {"city": "Nagasaki", "name": "Nagasaki Airport"},
    "KMJ": {"city": "Kumamoto", "name": "Kumamoto Airport"},
    "OIT": {"city": "Oita", "name": "Oita Airport"},
    "ICN": {"city": "Seoul", "name": "Incheon International Airport"},
    "GMP": {"city": "Seoul", "name": "Gimpo International Airport"},
    "PUS": {"city": "Busan", "name": "Gimhae International Airport"},
    "TPE": {"city": "Taipei", "name": "Taoyuan International Airport"},
    "TSA": {"city": "Taipei", "name": "Songshan Airport"},
    "KHH": {"city": "Kaohsiung", "name": "Kaohsiung International Airport"},
    "HKG": {"city": "Hong Kong", "name": "Hong Kong International Airport"},
    "PVG": {"city": "Shanghai", "name": "Pudong International Airport"},
    "SHA": {"city": "Shanghai", "name": "Hongqiao International Airport"},
    "PEK": {"city": "Beijing", "name": "Capital International Airport"},
    "PKX": {"city": "Beijing", "name": "Daxing International Airport"},
    "CAN": {"city": "Guangzhou", "name": "Baiyun International Airport"},
    "SZX": {"city": "Shenzhen", "name": "Bao'an International Airport"},
    "SIN": {"city": "Singapore", "name": "Changi Airport"},
    "BKK": {"city": "Bangkok", "name": "Suvarnabhumi Airport"},
    "DMK": {"city": "Bangkok", "name": "Don Mueang International Airport"},
    "SGN": {"city": "Ho Chi Minh City", "name": "Tan Son Nhat International Airport"},
    "HAN": {"city": "Hanoi", "name": "Noi Bai International Airport"},
    "DAD": {"city": "Da Nang", "name": "Da Nang International Airport"},
    "KUL": {"city": "Kuala Lumpur", "name": "Kuala Lumpur International Airport"},
    "MNL": {"city": "Manila", "name": "Ninoy Aquino International Airport"},
    "JKT": {"city": "Jakarta", "name": "Soekarno-Hatta International Airport"},
    "DPS": {"city": "Bali", "name": "Ngurah Rai International Airport"},
    "DEL": {"city": "Delhi", "name": "Indira Gandhi International Airport"},
    "BOM": {"city": "Mumbai", "name": "Chhatrapati Shivaji Maharaj International Airport"},
    "LHR": {"city": "London", "name": "Heathrow Airport"},
    "LGW": {"city": "London", "name": "Gatwick Airport"},
    "CDG": {"city": "Paris", "name": "Charles de Gaulle Airport"},
    "ORY": {"city": "Paris", "name": "Orly Airport"},
    "FRA": {"city": "Frankfurt", "name": "Frankfurt Airport"},
    "MUC": {"city": "Munich", "name": "Munich Airport"},
    "AMS": {"city": "Amsterdam", "name": "Schiphol Airport"},
    "MAD": {"city": "Madrid", "name": "Adolfo Suárez Madrid–Barajas Airport"},
    "BCN": {"city": "Barcelona", "name": "Josep Tarradellas Barcelona-El Prat Airport"},
    "FCO": {"city": "Rome", "name": "Fiumicino Airport"},
    "MXP": {"city": "Milan", "name": "Malpensa Airport"},
    "ZRH": {"city": "Zurich", "name": "Zurich Airport"},
    "VIE": {"city": "Vienna", "name": "Vienna International Airport"},
    "CPH": {"city": "Copenhagen", "name": "Copenhagen Airport"},
    "ARN": {"city": "Stockholm", "name": "Arlanda Airport"},
    "HEL": {"city": "Helsinki", "name": "Helsinki Airport"},
    "SVO": {"city": "Moscow", "name": "Sheremetyevo International Airport"},
    "IST": {"city": "Istanbul", "name": "Istanbul Airport"},
    "ATH": {"city": "Athens", "name": "Athens International Airport"},
    "JFK": {"city": "New York", "name": "John F. Kennedy International Airport"},
    "EWR": {"city": "Newark", "name": "Newark Liberty International Airport"},
    "LGA": {"city": "New York", "name": "LaGuardia Airport"},
    "LAX": {"city": "Los Angeles", "name": "Los Angeles International Airport"},
    "SFO": {"city": "San Francisco", "name": "San Francisco International Airport"},
    "ORD": {"city": "Chicago", "name": "O'Hare International Airport"},
    "SEA": {"city": "Seattle", "name": "Seattle-Tacoma International Airport"},
    "DFW": {"city": "Dallas", "name": "Dallas/Fort Worth International Airport"},
    "ATL": {"city": "Atlanta", "name": "Hartsfield-Jackson Atlanta International Airport"},
    "DEN": {"city": "Denver", "name": "Denver International Airport"},
    "MIA": {"city": "Miami", "name": "Miami International Airport"},
    "HNL": {"city": "Honolulu", "name": "Daniel K. Inouye International Airport"},
    "YVR": {"city": "Vancouver", "name": "Vancouver International Airport"},
    "YYZ": {"city": "Toronto", "name": "Toronto Pearson International Airport"},
    "MEX": {"city": "Mexico City", "name": "Benito Juárez International Airport"},
    "SYD": {"city": "Sydney", "name": "Kingsford Smith Airport"},
    "MEL": {"city": "Melbourne", "name": "Melbourne Airport"},
    "BNE": {"city": "Brisbane", "name": "Brisbane Airport"},
    "AKL": {"city": "Auckland", "name": "Auckland Airport"},
    "DXB": {"city": "Dubai", "name": "Dubai International Airport"},
    "AUH": {"city": "Abu Dhabi", "name": "Zayed International Airport"},
    "DOH": {"city": "Doha", "name": "Hamad International Airport"},
    "RUH": {"city": "Riyadh", "name": "King Khalid International Airport"},
    "JED": {"city": "Jeddah", "name": "King Abdulaziz International Airport"},
    "AMM": {"city": "Amman", "name": "Queen Alia International Airport"},
    "CAI": {"city": "Cairo", "name": "Cairo International Airport"},
    "CPT": {"city": "Cape Town", "name": "Cape Town International Airport"},
    "JNB": {"city": "Johannesburg", "name": "O.R. Tambo International Airport"},
    "GRU": {"city": "Sao Paulo", "name": "Guarulhos International Airport"},
    "GIG": {"city": "Rio de Janeiro", "name": "Galeao International Airport"},
    "EZE": {"city": "Buenos Aires", "name": "Ministro Pistarini International Airport"},
    "SCL": {"city": "Santiago", "name": "Arturo Merino Benitez International Airport"},
    "NCE": {"city": "Nice", "name": "Nice Côte d'Azur Airport"},

    # --- Restorations for data corrupted by Japanese translations ---
    "YEG": {"city": "Edmonton", "name": "Edmonton International Airport"},
    "YOW": {"city": "Ottawa", "name": "Ottawa Macdonald-Cartier International Airport"},
    "YUL": {"city": "Montreal", "name": "Montréal-Trudeau International Airport"},
    "YYC": {"city": "Calgary", "name": "Calgary International Airport"},
    "LOS": {"city": "Lagos", "name": "Murtala Muhammed International Airport"},
    "TUN": {"city": "Tunis", "name": "Tunis-Carthage International Airport"},
    "BRU": {"city": "Brussels", "name": "Brussels Airport"},
    "BER": {"city": "Berlin", "name": "Berlin Brandenburg Airport"},
    "HAM": {"city": "Hamburg", "name": "Hamburg Airport"},
    "DUS": {"city": "Dusseldorf", "name": "Dusseldorf Airport"},
    "STR": {"city": "Stuttgart", "name": "Stuttgart Airport"},
    "MAN": {"city": "Manchester", "name": "Manchester Airport"},
    "LTN": {"city": "London", "name": "Luton Airport"},
    "LCY": {"city": "London", "name": "London City Airport"},
    "EDI": {"city": "Edinburgh", "name": "Edinburgh Airport"},
    "STN": {"city": "London", "name": "London Stansted Airport"},
    "OSL": {"city": "Oslo", "name": "Oslo Airport"},
    "WAW": {"city": "Warsaw", "name": "Warsaw Chopin Airport"},
    "CMN": {"city": "Casablanca", "name": "Mohammed V International Airport"},
    "ADD": {"city": "Addis Ababa", "name": "Bole International Airport"},
    "NBO": {"city": "Nairobi", "name": "Jomo Kenyatta International Airport"},
    "BOS": {"city": "Boston", "name": "Logan International Airport"},
    "BWI": {"city": "Baltimore", "name": "Baltimore/Washington International Airport"},
    "CLT": {"city": "Charlotte", "name": "Charlotte Douglas International Airport"},
    "DAL": {"city": "Dallas", "name": "Dallas Love Field"},
    "DCA": {"city": "Washington, D.C.", "name": "Ronald Reagan Washington National Airport"},
    "DTW": {"city": "Detroit", "name": "Detroit Metropolitan Airport"},
    "FLL": {"city": "Fort Lauderdale", "name": "Fort Lauderdale-Hollywood International Airport"},
    "HOU": {"city": "Houston", "name": "William P. Hobby Airport"},
    "IAD": {"city": "Washington, D.C.", "name": "Dulles International Airport"},
    "IAH": {"city": "Houston", "name": "George Bush Intercontinental Airport"},
    "LAS": {"city": "Las Vegas", "name": "Harry Reid International Airport"},
    "MCO": {"city": "Orlando", "name": "Orlando International Airport"},
    "MDW": {"city": "Chicago", "name": "Midway International Airport"},
    "MSP": {"city": "Minneapolis", "name": "Minneapolis-Saint Paul International Airport"},
    "ORL": {"city": "Orlando", "name": "Orlando Executive Airport"},
    "PDX": {"city": "Portland", "name": "Portland International Airport"},
    "PHL": {"city": "Philadelphia", "name": "Philadelphia International Airport"},
    "PHX": {"city": "Phoenix", "name": "Phoenix Sky Harbor International Airport"},
    "SAN": {"city": "San Diego", "name": "San Diego International Airport"},
    "SLC": {"city": "Salt Lake City", "name": "Salt Lake City International Airport"},
    "TPA": {"city": "Tampa", "name": "Tampa International Airport"},
    "AGP": {"city": "Malaga", "name": "Malaga-Costa del Sol Airport"},
    "PMI": {"city": "Palma de Mallorca", "name": "Palma de Mallorca Airport"},
    "LYS": {"city": "Lyon", "name": "Lyon-Saint Exupéry Airport"},
    "MRS": {"city": "Marseille", "name": "Marseille Provence Airport"},
    "BUD": {"city": "Budapest", "name": "Ferenc Liszt International Airport"},
    "BGY": {"city": "Bergamo", "name": "Orio al Serio International Airport"},
    "LIN": {"city": "Milan", "name": "Linate Airport"},
    "VCE": {"city": "Venice", "name": "Venice Marco Polo Airport"},
    "CIA": {"city": "Rome", "name": "Ciampino Airport"},
    "NAP": {"city": "Naples", "name": "Naples International Airport"},
    "PRG": {"city": "Prague", "name": "Václav Havel Airport Prague"},
    "TLV": {"city": "Tel Aviv", "name": "Ben Gurion Airport"},
    "OPO": {"city": "Porto", "name": "Francisco Sá Carneiro Airport"},
    "LIS": {"city": "Lisbon", "name": "Humberto Delgado Airport"},
    "OTP": {"city": "Bucharest", "name": "Henri Coandă International Airport"},
    "GVA": {"city": "Geneva", "name": "Geneva Airport"},
    "ESB": {"city": "Ankara", "name": "Esenboğa Airport"},
    "SAW": {"city": "Istanbul", "name": "Sabiha Gökçen International Airport"},
    "CUN": {"city": "Cancun", "name": "Cancún International Airport"},
    "PTY": {"city": "Panama City", "name": "Tocumen International Airport"},
    "SJO": {"city": "San Jose", "name": "Juan Santamaría International Airport"},
    "NAN": {"city": "Nadi", "name": "Nadi International Airport"},
    "PPT": {"city": "Papeete", "name": "Fa'a'ā International Airport"},
    "NOU": {"city": "Noumea", "name": "La Tontouta International Airport"},
    "CHC": {"city": "Christchurch", "name": "Christchurch International Airport"},
    "WLG": {"city": "Wellington", "name": "Wellington International Airport"},
    "BAH": {"city": "Manama", "name": "Bahrain International Airport"},
    "DMM": {"city": "Dammam", "name": "King Fahd International Airport"},
    "THR": {"city": "Tehran", "name": "Imam Khomeini International Airport"},
    "KWI": {"city": "Kuwait", "name": "Kuwait International Airport"},
    "BEY": {"city": "Beirut", "name": "Beirut-Rafic Hariri International Airport"},
    "DWC": {"city": "Dubai", "name": "Al Maktoum International Airport"},
    "MCT": {"city": "Muscat", "name": "Muscat International Airport"},
    "KHI": {"city": "Karachi", "name": "Jinnah International Airport"},
    "LHE": {"city": "Lahore", "name": "Allama Iqbal International Airport"},
    "ANC": {"city": "Anchorage", "name": "Ted Stevens Anchorage International Airport"},
    "SPN": {"city": "Saipan", "name": "Saipan International Airport"},
    "GUM": {"city": "Guam", "name": "Antonio B. Won Pat International Airport"},
    "KOA": {"city": "Kona", "name": "Ellison Onizuka Kona International Airport"},
    "LIH": {"city": "Lihue", "name": "Lihue Airport"},
    "OGG": {"city": "Kahului", "name": "Kahului Airport"},
    "MMJ": {"city": "Matsumoto", "name": "Shinshu Matsumoto Airport"},
    "SHM": {"city": "Shirahama", "name": "Nanki Shirahama Airport"},
    "TJH": {"city": "Toyooka", "name": "Tajima Airport"},
    "HKD": {"city": "Hakodate", "name": "Hakodate Airport"},
    "OKD": {"city": "Sapporo", "name": "Okadama Airport"},
    "WKJ": {"city": "Wakkanai", "name": "Wakkanai Airport"},
    "IKI": {"city": "Iki", "name": "Iki Airport"},
    "UBJ": {"city": "Ube", "name": "Yamaguchi Ube Airport"},
    "TSJ": {"city": "Tsushima", "name": "Tsushima Airport"},
    "MBE": {"city": "Monbetsu", "name": "Monbetsu Airport"},
    "OIR": {"city": "Okushiri", "name": "Okushiri Airport"},
    "RIS": {"city": "Rishiri", "name": "Rishiri Airport"},
    "FUJ": {"city": "Goto", "name": "Fukue Airport"},
    "KKJ": {"city": "Kitakyushu", "name": "Kitakyushu Airport"},
    "HSG": {"city": "Saga", "name": "Saga Airport"},
    "ASJ": {"city": "Amami", "name": "Amami Airport"},
    "OKE": {"city": "Okinoerabu", "name": "Okinoerabu Airport"},
    "KKX": {"city": "Kikai", "name": "Kikai Airport"},
    "FKJ": {"city": "Fukui", "name": "Fukui Airport"},
    "OKI": {"city": "Okinoshima", "name": "Oki Airport"},
    "FSZ": {"city": "Shizuoka", "name": "Mt. Fuji Shizuoka Airport"},
    "TOY": {"city": "Toyama", "name": "Toyama Kitokito Airport"},
    "NTQ": {"city": "Wajima", "name": "Noto Airport"},
    "OKJ": {"city": "Okayama", "name": "Okayama Airport"},
    "IZO": {"city": "Izumo", "name": "Izumo Enmusubi Airport"},
    "YGJ": {"city": "Yonago", "name": "Yonago Kitaro Airport"},
    "KCZ": {"city": "Kochi", "name": "Kochi Ryoma Airport"},
    "TTJ": {"city": "Tottori", "name": "Tottori Sand Dunes Conan Airport"},
    "TKS": {"city": "Tokushima", "name": "Tokushima Awaodori Airport"},
    "IWJ": {"city": "Masuda", "name": "Hagi-Iwami Airport"},
    "FKS": {"city": "Fukushima", "name": "Fukushima Airport"},
    "HNA": {"city": "Hanamaki", "name": "Iwate Hanamaki Airport"},
    "AXT": {"city": "Akita", "name": "Akita Airport"},
    "ONJ": {"city": "Odate", "name": "Odate-Noshiro Airport"},
    "SYO": {"city": "Shonai", "name": "Shonai Airport"},
    "HAC": {"city": "Hachijojima", "name": "Hachijojima Airport"},
    "MYE": {"city": "Miyakejima", "name": "Miyakejima Airport"},
    "KWJ": {"city": "Gwangju", "name": "Gwangju Airport"},
    "CJU": {"city": "Jeju", "name": "Jeju International Airport"},
    "TAE": {"city": "Daegu", "name": "Daegu International Airport"},
    "ISG": {"city": "Ishigaki", "name": "New Ishigaki Airport"},
    "KJP": {"city": "Kerama", "name": "Kerama Airport"},
    "MMD": {"city": "Minamidaito", "name": "Minami Daito Airport"},
    "AGJ": {"city": "Aguni", "name": "Aguni Airport"},
    "IEJ": {"city": "Iejima", "name": "Ie Jima Airport"},
    "HTR": {"city": "Hateruma", "name": "Hateruma Airport"},
    "KTD": {"city": "Kitadaito", "name": "Kitadaito Airport"},
    "SHI": {"city": "Shimojishima", "name": "Shimojishima Airport"},
    "TRA": {"city": "Tarama", "name": "Tarama Airport"},
    "RNJ": {"city": "Yoron", "name": "Yoron Airport"},
    "OGN": {"city": "Yonaguni", "name": "Yonaguni Airport"},
    "CEB": {"city": "Cebu", "name": "Mactan-Cebu International Airport"},
    "AEP": {"city": "Buenos Aires", "name": "Jorge Newbery Airfield"},
    "BSB": {"city": "Brasilia", "name": "Brasilia International Airport"},
    "SDU": {"city": "Rio de Janeiro", "name": "Santos Dumont Airport"},
    "CGH": {"city": "Sao Paulo", "name": "Congonhas Airport"},
    "UIO": {"city": "Quito", "name": "Mariscal Sucre International Airport"},
    "BOG": {"city": "Bogota", "name": "El Dorado International Airport"},
    "LIM": {"city": "Lima", "name": "Jorge Chávez International Airport"},
    "KBP": {"city": "Kyiv", "name": "Boryspil International Airport"},
    "IEV": {"city": "Kyiv", "name": "Igor Sikorsky Kyiv International Airport"},
    "LED": {"city": "Saint Petersburg", "name": "Pulkovo Airport"},
    "DME": {"city": "Moscow", "name": "Domodedovo Airport"},
    "VKO": {"city": "Moscow", "name": "Vnukovo International Airport"},
    "CMB": {"city": "Colombo", "name": "Bandaranaike International Airport"},
    "PNH": {"city": "Phnom Penh", "name": "Phnom Penh International Airport"},
    "REP": {"city": "Siem Reap", "name": "Siem Reap Angkor International Airport"},
    "CCU": {"city": "Kolkata", "name": "Netaji Subhash Chandra Bose International Airport"},
    "DAC": {"city": "Dhaka", "name": "Hazrat Shahjalal International Airport"},
    "VTE": {"city": "Vientiane", "name": "Wattay International Airport"},
    "MFM": {"city": "Macau", "name": "Macau International Airport"},
    "KTM": {"city": "Kathmandu", "name": "Tribhuvan International Airport"},
    "BLR": {"city": "Bengaluru", "name": "Kempegowda International Airport"},
    "COK": {"city": "Kochi", "name": "Cochin International Airport"},
    "HYD": {"city": "Hyderabad", "name": "Rajiv Gandhi International Airport"},
    "MAA": {"city": "Chennai", "name": "Chennai International Airport"},
    "MLE": {"city": "Male", "name": "Velana International Airport"},
    "CNX": {"city": "Chiang Mai", "name": "Chiang Mai International Airport"},
    "HKT": {"city": "Phuket", "name": "Phuket International Airport"},
    "RGN": {"city": "Yangon", "name": "Yangon International Airport"},
    "SUB": {"city": "Surabaya", "name": "Juanda International Airport"},
    "BKI": {"city": "Kota Kinabalu", "name": "Kota Kinabalu International Airport"},
    "BWN": {"city": "Bandar Seri Begawan", "name": "Brunei International Airport"},
    "PEN": {"city": "Penang", "name": "Penang International Airport"},
    "OOL": {"city": "Gold Coast", "name": "Gold Coast Airport"},
    "CNS": {"city": "Cairns", "name": "Cairns Airport"},
    "ADL": {"city": "Adelaide", "name": "Adelaide Airport"},
    "PER": {"city": "Perth", "name": "Perth Airport"},
    "WUH": {"city": "Wuhan", "name": "Wuhan Tianhe International Airport"},
    "XIY": {"city": "Xi'an", "name": "Xi'an Xianyang International Airport"},
    "KMG": {"city": "Kunming", "name": "Kunming Changshui International Airport"},
    "XMN": {"city": "Xiamen", "name": "Xiamen Gaoqi International Airport"},
    "HGH": {"city": "Hangzhou", "name": "Hangzhou Xiaoshan International Airport"},
    "NKG": {"city": "Nanjing", "name": "Nanjing Lukou International Airport"},
    "TAO": {"city": "Qingdao", "name": "Qingdao Jiaodong International Airport"},
    "CKG": {"city": "Chongqing", "name": "Chongqing Jiangbei International Airport"},
    "TFU": {"city": "Chengdu", "name": "Chengdu Tianfu International Airport"},
    "CTU": {"city": "Chengdu", "name": "Chengdu Shuangliu International Airport"},
    "DLC": {"city": "Dalian", "name": "Dalian Zhoushuizi International Airport"},
    
    # Missing 5 fix
    "KEF": {"city": "Reykjavik", "name": "Keflavík International Airport"},
    "DUB": {"city": "Dublin", "name": "Dublin Airport"},
    "RAK": {"city": "Marrakesh", "name": "Marrakesh Menara Airport"},
    "PMO": {"city": "Palermo", "name": "Falcone Borsellino Airport"},
    "CGK": {"city": "Jakarta", "name": "Soekarno-Hatta International Airport"}
}

# Keep this for JA additions (it is correct)
JA_ADDITIONS = {
    # USA
    "LAS": {"city": "ラスベガス", "name": "ハリー・リード国際空港"},
    "MCO": {"city": "オーランド", "name": "オーランド国際空港"},
    "IAD": {"city": "ワシントンD.C.", "name": "ダレス国際空港"},
    "DCA": {"city": "ワシントンD.C.", "name": "ロナルド・レーガン・ワシントン・ナショナル空港"},
    "BOS": {"city": "ボストン", "name": "ローガン国際空港"},
    "PHL": {"city": "フィラデルフィア", "name": "フィラデルフィア国際空港"},
    "CLT": {"city": "シャーロット", "name": "シャーロット・ダグラス国際空港"},
    "MSP": {"city": "ミネアポリス", "name": "ミネアポリス・セントポール国際空港"},
    "DTW": {"city": "デトロイト", "name": "デトロイト・メトロポリタン空港"},
    "SLC": {"city": "ソルトレイクシティ", "name": "ソルトレイクシティ国際空港"},
    "FLL": {"city": "フォートローダーデール", "name": "フォートローダーデール・ハリウッド国際空港"},
    "BWI": {"city": "ボルチモア", "name": "ボルチモア・ワシントン国際空港"},
    "SAN": {"city": "サンディエゴ", "name": "サンディエゴ国際空港"},
    "TPA": {"city": "タンパ", "name": "タンパ国際空港"},
    "PDX": {"city": "ポートランド", "name": "ポートランド国際空港"},
    "GUM": {"city": "グアム", "name": "アントニオ・B・ウォン・パット国際空港"},
    "SPN": {"city": "サイパン", "name": "サイパン国際空港"},

    # Europe
    "ZRH": {"city": "チューリッヒ", "name": "チューリッヒ空港"},
    "GVA": {"city": "ジュネーヴ", "name": "ジュネーヴ空港"},
    "BRU": {"city": "ブリュッセル", "name": "ブリュッセル空港"},
    "DUB": {"city": "ダブリン", "name": "ダブリン空港"},
    "LIS": {"city": "リスボン", "name": "ウンベルト・デルガード空港"},
    "OPO": {"city": "ポルト", "name": "フランシスコ・サ・カルネイロ空港"},
    "OSL": {"city": "オスロ", "name": "オスロ空港"},
    "WAW": {"city": "ワルシャワ", "name": "ワルシャワ・ショパン空港"},
    "BUD": {"city": "ブダペスト", "name": "リスト・フェレンツ国際空港"},
    "PRG": {"city": "プラハ", "name": "ヴァーツラフ・ハヴェル・プラハ国際空港"},
    "VCE": {"city": "ヴェネツィア", "name": "ヴェネツィア・テッセラ空港"},
    "NAP": {"city": "ナポリ", "name": "ナポリ・カポディキーノ国際空港"},
    "PMO": {"city": "パレルモ", "name": "ファルコーネ・ボルセリーノ空港"},
    "KEF": {"city": "レイキャビク", "name": "ケフラヴィーク国際空港"},

    # Asia / Oceania
    "CGK": {"city": "ジャカルタ", "name": "スカルノ・ハッタ国際空港"},
    "KTM": {"city": "カトマンズ", "name": "トリブバン国際空港"},
    "MLE": {"city": "マレ", "name": "ヴェラナ国際空港"},
    "CMB": {"city": "コロンボ", "name": "バンダラナイケ国際空港"},
    "PEN": {"city": "ペナン", "name": "ペナン国際空港"},
    "HKT": {"city": "プーケット", "name": "プーケット国際空港"},
    "CNX": {"city": "チェンマイ", "name": "チェンマイ国際空港"},
    "CEB": {"city": "セブ", "name": "マクタン・セブ国際空港"},
    "PER": {"city": "パース", "name": "パース空港"},
    "ADL": {"city": "アデレード", "name": "アデレード空港"},
    "CHC": {"city": "クライストチャーチ", "name": "クライストチャーチ国際空港"},
    "PPT": {"city": "タヒチ", "name": "ファアア国際空港"},
    "NOU": {"city": "ヌメア", "name": "ラ・トントゥータ国際空港"},
    "NAN": {"city": "ナンディ", "name": "ナンディ国際空港"},

    # Middle East / Africa
    "TLV": {"city": "テルアビブ", "name": "ベン・グリオン国際空港"},
    "MCT": {"city": "マスカット", "name": "マスカット国際空港"},
    "CMN": {"city": "カサブランカ", "name": "ムハンマド5世国際空港"},
    "RAK": {"city": "マラケシュ", "name": "マラケシュ・メナラ空港"},
    "NBO": {"city": "ナイロビ", "name": "ジョモ・ケニヤッタ国際空港"},
    "ADD": {"city": "アディスアベバ", "name": "ボレ国際空港"},
    
    # Americas
    "YYC": {"city": "カルガリー", "name": "カルガリー国際空港"},
    "YUL": {"city": "モントリオール", "name": "ピエール・エリオット・トルドー国際空港"},
    "LIM": {"city": "リマ", "name": "ホルヘ・チャベス国際空港"},
    "BOG": {"city": "ボゴタ", "name": "エルドラド国際空港"},
    "CUN": {"city": "カンクン", "name": "カンクン国際空港"}
}

def restore_english(record):
    iata = record.get("iata", "").strip()
    if iata in EN_RESTORATIONS:
        new_rec = record.copy()
        new_rec["city"] = EN_RESTORATIONS[iata]["city"]
        new_rec["name"] = EN_RESTORATIONS[iata]["name"]
        return new_rec
    return record

def apply_japanese(record):
    iata = record.get("iata", "").strip()
    if iata in JA_ADDITIONS:
        new_rec = record.copy()
        new_rec["city"] = JA_ADDITIONS[iata]["city"]
        new_rec["name"] = JA_ADDITIONS[iata]["name"]
        return new_rec
    return record

def main():
    base_dir = "src/assets"
    
    # Source is now the JA file we just created (since original was deleted)
    ja_dir = os.path.join(base_dir, "locales", "ja")
    source = os.path.join(ja_dir, "airports.json")
    
    en_dir = os.path.join(base_dir, "locales", "en")
    
    if not os.path.exists(source):
        print(f"Error: Source file {source} not found.")
        return

    with open(source, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    # JA: Apply Additions
    ja_data = [apply_japanese(rec) for rec in data]
    with open(os.path.join(ja_dir, "airports.json"), 'w', encoding='utf-8') as f:
        json.dump(ja_data, f, ensure_ascii=False, indent=2)
        print(f"Updated JA dataset at {ja_dir}/airports.json with {len(JA_ADDITIONS)} translations")

    # EN: Restore translations
    # We are restoring from the data we just loaded (which is technically JA_DATA now in this flow)
    # But restore_english uses the IATA key to overwrite completely, so it's safe.
    en_data = [restore_english(rec) for rec in data]
    
    with open(os.path.join(en_dir, "airports.json"), 'w', encoding='utf-8') as f:
        json.dump(en_data, f, ensure_ascii=False, indent=2)
        print(f"Updated EN dataset at {en_dir}/airports.json")

if __name__ == "__main__":
    main()
